#!/bin/bash

# 100 Safe for Work motivational/fun phrases
COWSAY_QUOTES=(
  "Linux: where the root is strong."
  "Uptime is a virtue."
  "May your permissions always be correct."
  "There's no place like /home."
  "Ctrl+C your worries away."
  "Keep calm and sudo on."
  "Be the root of all problems—intentionally."
  "alias life='sudo make it work'"
  "When in doubt, man it out."
  "Bash it 'til it works."
  "In Linux we trust."
  "Shell yeah!"
  "Permission denied? Challenge accepted."
  "Sudoers gonna sudo."
  "df -h and know your limits."
  "You had me at 'Linux'."
  "Less GUI, more do-ey."
  "uname -a, because I can."
  "Linux users do it in the terminal."
  "cd ~ && stay cozy."
  "Bugs fear the power of chmod +x."
  "echo 'Hello, $USER!'"
  "Nothing beats a clean dmesg."
  "Every day is sysadmin appreciation day."
  "kill -9 bad vibes."
  "rm -rf imposter syndrome."
  "Linux: It's not a phase, mom!"
  "Terminally awesome."
  "Why click when you can grep?"
  "Linux is my escape sequence."
  "Kernel of truth: I love Linux."
  "Log files never lie."
  "There is no place like 127.0.0.1"
  "Scripting my way through life."
  "sudo apt install happiness"
  "top - you’re always at the top."
  "Cron jobs never sleep."
  "awkward? Nah, just awk-savvy."
  "A shell a day keeps the GUI away."
  "Keep your logs clean and your mounts stable."
  "Life's better with root access."
  "Your shell is your sanctuary."
  "sudo bash your way to success."
  "Who needs windows anyway?"
  "Linux is case sensitive, just like me."
  "chmod +x your dreams."
  "You are the command line hero."
  "init 0 your doubts."
  "Where there's a shell, there's a way."
  "Stay calm and tail -f /var/log/syslog"
  "Reboot your mindset."
  "Linux is love. Linux is life."
  "One does not simply exit Vim."
  "The only blue screen is my wallpaper."
  "Debian or die tryin’."
  "Systemd is watching you."
  "Life without logs is meaningless."
  "Linux users have better uptime."
  "sudo gives me superpowers."
  "Forget Mac, forget Windows—I'm terminally committed."
  "Linux: Because rebooting is for upgrades."
  "df -i your life."
  "Linux > everything else."
  "My happy place? /etc/"
  "grep the day!"
  "No swap, no excuses."
  "Even my coffee runs on Linux."
  "sudo make me a sandwich"
  "I speak fluent bash."
  "I dream in cron expressions."
  "Built with open-source love."
  "Who needs luck when you have logs?"
  "My other computer is a Raspberry Pi."
  "Because typing is faster than clicking."
  "Logs are just journals for your system’s feelings."
  "Nothing a reboot can’t fix (unless it’s a production server)."
  "Every good day starts with a good prompt."
  "echo $PATH to enlightenment."
  "Give me Linux or give me a kernel panic!"
  "Life’s better in /var/tmp"
  "I like my OS like I like my code: open."
  "Don't feed the daemons."
  "Keep your processes in check with htop."
  "sudo: because you deserve it."
  "The terminal is my playground."
  "No GUI? No problem."
  "Ping is my love language."
  "127.0.0.1 is where the home is."
  "Tab completion is the real MVP."
  "Break it. Fix it. Log it."
  "On Wednesdays we wear root."
  "Mind your mounts."
  "Hack the planet—with a package manager!"
  "May all your processes fork gracefully."
  "It's not magic, it's just Linux."
  "Raise your limits.conf!"
  "Get in, loser. We’re compiling the kernel."
  "Clean boots, clean conscience."
  "Don’t just install it—build it from source."
  "rm: it is dangerous to operate recursively on '/'"
  "Use --no-preserve-root to override this failsafe (but seriously, don't)."
  "Don't try 'mkfs.ext4 /dev/sda' unless you're bored with life."
  "Running 'dd if=/dev/zero of=/dev/sda' is not a fun party trick."
  "'chmod -R 777 /' – that's one way to make friends... and enemies."
  "Remember: 'fork bombs' are not desserts."
  "':(){ :|:& };:' – This is not a smiley face. Don’t run it."
  "'sudo rm -rf /' – Not even once."
  "Don't sudo things you can't unsudo."
  "If it needs 'yes |', it probably needs a second thought."
 )

RANDOM_QUOTE="${COWSAY_QUOTES[$RANDOM % ${#COWSAY_QUOTES[@]}]}"
cowsay "$RANDOM_QUOTE"

